name: sls
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  agora_rtc_engine: ^5.0.1
  intl:
  gallery_saver: ^2.2.0
  flutter_native_splash: ^2.1.6
  bloc: ^7.0.0
  image_gallery_saver: ^1.7.1
  flutter_bloc: ^7.1.0
  http:
  shared_preferences: ^2.0.15
  flutter_hex_color: ^2.0.0
  contained_tab_bar_view: ^0.8.0
  search_page: ^2.0.0+1
  flutter_svg: ^1.1.1
  flick_video_player: ^0.5.0
  flag: ^6.0.0
  modal_bottom_sheet: ^2.1.0
  expandable_search_bar: ^0.0.1
  firebase_auth:
  cloud_firestore: ^3.1.14
  #firebase_auth_platform_interface: ^6.1.10
  flutter_launcher_icons: "^0.9.2"
  google_sign_in: ^5.4.0
  flutter_facebook_auth: ^4.4.0+1
  firebase_storage: ^10.3.4
  image_picker: ^0.8.5+3
  expandable_text: 2.3.0
  firebase_database: ^9.1.0
  file_picker: ^5.2.2
  modal_progress_hud_nsn:
  timeago:
  provider:
  like_button: ^2.0.4
  mime_type: ^1.0.0
  mime: ^1.0.2
  path_provider:
  cached_network_image:
  permission_handler: ^10.2.0
  uuid:
  native_screenshot:
  fijkplayer:
  time_ago_provider:
  dotted_border:
  fluttertoast: ^8.0.9
  screenshot:
  firebase_core:
  #firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^13.0.4
  video_player:
  device_preview:
  onesignal_flutter:
  emoji_picker:
  flutter_keyboard_visibility:
  flutter_local_notifications: ^9.6.0
  timezone: ^0.8.0
  rxdart: ^0.27.4
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo1.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
    #f59b1aed-1d50-4c5e-923c-ae55385d4420

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

flutter_native_splash:
  color: "#f7b6b8"
  android: true
  ios: true
  image: assets/logo.png
  web: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/profile_icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
